import type { Product } from "@/types/product";

const createdAt = new Date("2026-01-10T12:00:00.000Z");
const updatedAt = new Date("2026-01-10T12:00:00.000Z");

const localImages = {
  editorialWide: "/products/zara3.webp",
  studioPortrait: "/products/images.jpg",
  studioClose: "/products/images (1).jpg",
  softLook: "/products/450e.avif",
} as const;

export const mockProducts: Product[] = [
  {
    id: "prod-jean-wide-leg-celeste",
    name: "Jean Wide Leg Celeste",
    slug: "jean-wide-leg-celeste",
    description:
      "Jean wide leg de tiro alto en denim celeste, pensado para looks urbanos cómodos y frescos.",
    price: 49900,
    category: "jeans",
    sizes: ["36", "38", "40", "42"],
    colors: ["Celeste", "Azul denim"],
    stockStatus: "available",
    images: [
      {
        url: localImages.editorialWide,
        alt: "Modelo con look editorial en blanco y negro para Jean Wide Leg Celeste",
        position: 0,
      },
      {
        url: localImages.studioClose,
        alt: "Detalle editorial blanco y negro para Jean Wide Leg Celeste",
        position: 1,
      },
    ],
    isVisible: true,
    isFeatured: true,
    isNewArrival: true,
    createdAt,
    updatedAt,
  },
  {
    id: "prod-top-morley-bordo",
    name: "Top Morley Bordó",
    slug: "top-morley-bordo",
    description:
      "Top de morley bordó con ajuste al cuerpo, ideal para combinar con denim o sastrería.",
    price: 25900,
    category: "tops",
    sizes: ["S", "M", "L"],
    colors: ["Bordó"],
    stockStatus: "ask_stock",
    images: [
      {
        url: localImages.softLook,
        alt: "Top Morley Bordó en fotografía editorial blanco y negro",
        position: 0,
      },
    ],
    isVisible: true,
    isFeatured: true,
    isNewArrival: true,
    createdAt,
    updatedAt,
  },
  {
    id: "prod-sweater-tejido-chocolate",
    name: "Sweater Tejido Chocolate",
    slug: "sweater-tejido-chocolate",
    description:
      "Sweater tejido en tono chocolate, suave y abrigado para elevar looks diarios.",
    price: 42900,
    category: "sweaters",
    sizes: ["S", "M", "L"],
    colors: ["Chocolate", "Marrón"],
    stockStatus: "available",
    images: [
      {
        url: localImages.studioClose,
        alt: "Sweater Tejido Chocolate en editorial de moda blanco y negro",
        position: 0,
      },
    ],
    isVisible: true,
    isFeatured: true,
    isNewArrival: false,
    createdAt,
    updatedAt,
  },
  {
    id: "prod-campera-negra-urbana",
    name: "Campera Negra Urbana",
    slug: "campera-negra-urbana",
    description:
      "Campera negra de silueta urbana, fácil de sumar a outfits de día y noche.",
    price: 68900,
    category: "camperas",
    sizes: ["S", "M", "L"],
    colors: ["Negro"],
    stockStatus: "available",
    images: [
      {
        url: localImages.studioPortrait,
        alt: "Campera Negra Urbana en fotografía editorial blanco y negro",
        position: 0,
      },
    ],
    isVisible: true,
    isFeatured: false,
    isNewArrival: true,
    createdAt,
    updatedAt,
  },
  {
    id: "prod-pantalon-sastrero-negro",
    name: "Pantalón Sastrero Negro",
    slug: "pantalon-sastrero-negro",
    description:
      "Pantalón sastrero negro de corte recto, una base elegante para cualquier temporada.",
    price: 53900,
    category: "pantalones",
    sizes: ["36", "38", "40", "42"],
    colors: ["Negro"],
    stockStatus: "sold_out",
    images: [
      {
        url: localImages.editorialWide,
        alt: "Pantalón Sastrero Negro en editorial de moda blanco y negro",
        position: 0,
      },
    ],
    isVisible: true,
    isFeatured: false,
    isNewArrival: false,
    createdAt,
    updatedAt,
  },
  {
    id: "prod-buzo-off-white",
    name: "Buzo Off White",
    slug: "buzo-off-white",
    description:
      "Buzo off white de ajuste relajado, cómodo y versátil para looks casuales.",
    price: 37900,
    category: "buzos",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Off white"],
    stockStatus: "available",
    images: [
      {
        url: localImages.studioClose,
        alt: "Buzo Off White en fotografía editorial blanco y negro",
        position: 0,
      },
    ],
    isVisible: true,
    isFeatured: false,
    isNewArrival: true,
    createdAt,
    updatedAt,
  },
  {
    id: "prod-remera-vintage",
    name: "Remera Vintage",
    slug: "remera-vintage",
    description:
      "Remera de inspiración vintage con textura suave, pensada para uso diario.",
    price: 21900,
    category: "tops",
    sizes: ["S", "M", "L"],
    colors: ["Grafito", "Gris lavado"],
    stockStatus: "available",
    images: [
      {
        url: localImages.softLook,
        alt: "Remera Vintage en fotografía editorial blanco y negro",
        position: 0,
      },
    ],
    isVisible: true,
    isFeatured: false,
    isNewArrival: false,
    createdAt,
    updatedAt,
  },
  {
    id: "prod-cargo-denim",
    name: "Cargo Denim",
    slug: "cargo-denim",
    description: "Pantalón cargo denim con bolsillos laterales y actitud urbana.",
    price: 57900,
    category: "jeans",
    sizes: ["36", "38", "40", "42"],
    colors: ["Azul denim"],
    stockStatus: "ask_stock",
    images: [
      {
        url: localImages.editorialWide,
        alt: "Cargo Denim en fotografía editorial blanco y negro",
        position: 0,
      },
    ],
    isVisible: true,
    isFeatured: false,
    isNewArrival: true,
    createdAt,
    updatedAt,
  },
  {
    id: "prod-polera-basica-blanca",
    name: "Polera Básica Blanca",
    slug: "polera-basica-blanca",
    description:
      "Polera blanca básica de cuello alto, liviana y fácil de combinar.",
    price: 29900,
    category: "tops",
    sizes: ["S", "M", "L"],
    colors: ["Blanco"],
    stockStatus: "available",
    images: [
      {
        url: localImages.studioPortrait,
        alt: "Polera Básica Blanca en fotografía editorial blanco y negro",
        position: 0,
      },
    ],
    isVisible: true,
    isFeatured: true,
    isNewArrival: false,
    createdAt,
    updatedAt,
  },
  {
    id: "prod-conjunto-gris-y-negro",
    name: "Conjunto Gris y Negro",
    slug: "conjunto-gris-y-negro",
    description:
      "Conjunto gris y negro de dos piezas, cómodo y pulido para resolver el look completo.",
    price: 74900,
    category: "conjuntos",
    sizes: ["S", "M", "L"],
    colors: ["Gris", "Negro"],
    stockStatus: "available",
    images: [
      {
        url: localImages.studioPortrait,
        alt: "Conjunto Gris y Negro en fotografía editorial blanco y negro",
        position: 0,
      },
    ],
    isVisible: true,
    isFeatured: true,
    isNewArrival: true,
    createdAt,
    updatedAt,
  },
  {
    id: "prod-accesorio-cartera-bordo",
    name: "Cartera Bordó Mini",
    slug: "cartera-bordo-mini",
    description:
      "Cartera mini bordó para sumar un acento femenino y cálido al outfit.",
    price: 32900,
    category: "accesorios",
    sizes: ["Único"],
    colors: ["Bordó"],
    stockStatus: "available",
    images: [
      {
        url: localImages.softLook,
        alt: "Cartera Bordó Mini en fotografía editorial blanco y negro",
        position: 0,
      },
    ],
    isVisible: false,
    isFeatured: false,
    isNewArrival: false,
    createdAt,
    updatedAt,
  },
];
