import type { Product } from "@/types/product";

const createdAt = new Date("2026-01-10T12:00:00.000Z");
const updatedAt = new Date("2026-01-10T12:00:00.000Z");

const localImages = {
  editorialWide: "/products/zara3.webp",
  studioPortrait: "/products/images.jpg",
  studioClose: "/products/images (1).jpg",
  softLook: "/products/450e.avif",
} as const;

export const mockProducts: Product[] = [
  {
    id: "prod-jean-wide-leg-celeste",
    name: "Jean celeste de corte amplio",
    slug: "jean-wide-leg-celeste",
    description:
      "Jean de tiro alto y pierna amplia en tela celeste, pensado para conjuntos urbanos cómodos y frescos.",
    price: 49900,
    category: "jeans",
    sizes: ["36", "38", "40", "42"],
    colors: ["Celeste", "Azul jean"],
    stockStatus: "available",
    images: [
      {
        url: localImages.editorialWide,
        alt: "Modelo con conjunto editorial para jean celeste de corte amplio",
        position: 0,
      },
      {
        url: localImages.studioClose,
        alt: "Detalle editorial para jean celeste de corte amplio",
        position: 1,
      },
    ],
    isVisible: true,
    isFeatured: true,
    isNewArrival: true,
    createdAt,
    updatedAt,
  },
  {
    id: "prod-top-morley-bordo",
    name: "Remera de morley bordó",
    slug: "top-morley-bordo",
    description:
      "Remera de morley bordó con ajuste al cuerpo, ideal para combinar con jeans o sastrería.",
    price: 25900,
    category: "tops",
    sizes: ["S", "M", "L"],
    colors: ["Bordó"],
    stockStatus: "ask_stock",
    images: [
      {
        url: localImages.softLook,
        alt: "Remera de morley bordó en fotografía editorial",
        position: 0,
      },
    ],
    isVisible: true,
    isFeatured: true,
    isNewArrival: true,
    createdAt,
    updatedAt,
  },
  {
    id: "prod-sweater-tejido-chocolate",
    name: "Suéter tejido color chocolate",
    slug: "sweater-tejido-chocolate",
    description:
      "Suéter tejido en tono chocolate, suave y abrigado para realzar conjuntos cotidianos.",
    price: 42900,
    category: "sweaters",
    sizes: ["S", "M", "L"],
    colors: ["Chocolate", "Marrón"],
    stockStatus: "available",
    images: [
      {
        url: localImages.studioClose,
        alt: "Suéter tejido color chocolate en fotografía editorial",
        position: 0,
      },
    ],
    isVisible: true,
    isFeatured: true,
    isNewArrival: false,
    createdAt,
    updatedAt,
  },
  {
    id: "prod-campera-negra-urbana",
    name: "Campera Negra Urbana",
    slug: "campera-negra-urbana",
    description:
      "Campera negra de silueta urbana, fácil de sumar a conjuntos de día y noche.",
    price: 68900,
    category: "camperas",
    sizes: ["S", "M", "L"],
    colors: ["Negro"],
    stockStatus: "available",
    images: [
      {
        url: localImages.studioPortrait,
        alt: "Campera Negra Urbana en fotografía editorial blanco y negro",
        position: 0,
      },
    ],
    isVisible: true,
    isFeatured: false,
    isNewArrival: true,
    createdAt,
    updatedAt,
  },
  {
    id: "prod-pantalon-sastrero-negro",
    name: "Pantalón Sastrero Negro",
    slug: "pantalon-sastrero-negro",
    description:
      "Pantalón sastrero negro de corte recto, una base elegante para cualquier temporada.",
    price: 53900,
    category: "pantalones",
    sizes: ["36", "38", "40", "42"],
    colors: ["Negro"],
    stockStatus: "sold_out",
    images: [
      {
        url: localImages.editorialWide,
        alt: "Pantalón Sastrero Negro en editorial de moda blanco y negro",
        position: 0,
      },
    ],
    isVisible: true,
    isFeatured: false,
    isNewArrival: false,
    createdAt,
    updatedAt,
  },
  {
    id: "prod-buzo-off-white",
    name: "Buzo blanco crudo",
    slug: "buzo-off-white",
    description:
      "Buzo blanco crudo de ajuste relajado, cómodo y versátil para combinaciones informales.",
    price: 37900,
    category: "buzos",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blanco crudo"],
    stockStatus: "available",
    images: [
      {
        url: localImages.studioClose,
        alt: "Buzo blanco crudo en fotografía editorial",
        position: 0,
      },
    ],
    isVisible: true,
    isFeatured: false,
    isNewArrival: true,
    createdAt,
    updatedAt,
  },
  {
    id: "prod-remera-vintage",
    name: "Remera de estilo clásico",
    slug: "remera-vintage",
    description:
      "Remera de inspiración clásica con textura suave, pensada para uso diario.",
    price: 21900,
    category: "tops",
    sizes: ["S", "M", "L"],
    colors: ["Grafito", "Gris lavado"],
    stockStatus: "available",
    images: [
      {
        url: localImages.softLook,
        alt: "Remera de estilo clásico en fotografía editorial",
        position: 0,
      },
    ],
    isVisible: true,
    isFeatured: false,
    isNewArrival: false,
    createdAt,
    updatedAt,
  },
  {
    id: "prod-cargo-denim",
    name: "Jean cargo",
    slug: "cargo-denim",
    description: "Jean cargo con bolsillos laterales y actitud urbana.",
    price: 57900,
    category: "jeans",
    sizes: ["36", "38", "40", "42"],
    colors: ["Azul jean"],
    stockStatus: "ask_stock",
    images: [
      {
        url: localImages.editorialWide,
        alt: "Jean cargo en fotografía editorial",
        position: 0,
      },
    ],
    isVisible: true,
    isFeatured: false,
    isNewArrival: true,
    createdAt,
    updatedAt,
  },
  {
    id: "prod-polera-basica-blanca",
    name: "Polera Básica Blanca",
    slug: "polera-basica-blanca",
    description:
      "Polera blanca básica de cuello alto, liviana y fácil de combinar.",
    price: 29900,
    category: "tops",
    sizes: ["S", "M", "L"],
    colors: ["Blanco"],
    stockStatus: "available",
    images: [
      {
        url: localImages.studioPortrait,
        alt: "Polera Básica Blanca en fotografía editorial blanco y negro",
        position: 0,
      },
    ],
    isVisible: true,
    isFeatured: true,
    isNewArrival: false,
    createdAt,
    updatedAt,
  },
  {
    id: "prod-conjunto-gris-y-negro",
    name: "Conjunto Gris y Negro",
    slug: "conjunto-gris-y-negro",
    description:
      "Conjunto gris y negro de dos piezas, cómodo y cuidado para resolver la combinación completa.",
    price: 74900,
    category: "conjuntos",
    sizes: ["S", "M", "L"],
    colors: ["Gris", "Negro"],
    stockStatus: "available",
    images: [
      {
        url: localImages.studioPortrait,
        alt: "Conjunto Gris y Negro en fotografía editorial blanco y negro",
        position: 0,
      },
    ],
    isVisible: true,
    isFeatured: true,
    isNewArrival: true,
    createdAt,
    updatedAt,
  },
  {
    id: "prod-accesorio-cartera-bordo",
    name: "Cartera bordó pequeña",
    slug: "cartera-bordo-mini",
    description:
      "Cartera bordó pequeña para sumar un acento femenino y cálido al conjunto.",
    price: 32900,
    category: "accesorios",
    sizes: ["Único"],
    colors: ["Bordó"],
    stockStatus: "available",
    images: [
      {
        url: localImages.softLook,
        alt: "Cartera bordó pequeña en fotografía editorial",
        position: 0,
      },
    ],
    isVisible: false,
    isFeatured: false,
    isNewArrival: false,
    createdAt,
    updatedAt,
  },
];
