import type { Product } from "@/types/product";

const createdAt = new Date("2026-01-10T12:00:00.000Z");
const updatedAt = new Date("2026-01-10T12:00:00.000Z");

export const mockProducts: Product[] = [
  {
    id: "prod-jean-wide-leg-celeste",
    name: "Jean Wide Leg Celeste",
    slug: "jean-wide-leg-celeste",
    description:
      "Jean wide leg de tiro alto en denim celeste, pensado para looks urbanos comodos y frescos.",
    price: 49900,
    category: "jeans",
    sizes: ["36", "38", "40", "42"],
    colors: ["Celeste", "Azul denim"],
    stockStatus: "available",
    images: [
      {
        url: "/images/products/jean-wide-leg-celeste/main.webp",
        path: "products/prod-jean-wide-leg-celeste/main.webp",
        alt: "Jean wide leg celeste de tiro alto",
        position: 0,
      },
    ],
    isVisible: true,
    isFeatured: true,
    isNewArrival: true,
    createdAt,
    updatedAt,
  },
  {
    id: "prod-top-morley-bordo",
    name: "Top Morley Bordó",
    slug: "top-morley-bordo",
    description:
      "Top de morley bordó con calce al cuerpo, ideal para combinar con denim o sastreria.",
    price: 25900,
    category: "tops",
    sizes: ["S", "M", "L"],
    colors: ["Bordó"],
    stockStatus: "ask_stock",
    images: [
      {
        url: "/images/products/top-morley-bordo/main.webp",
        path: "products/prod-top-morley-bordo/main.webp",
        alt: "Top morley bordó femenino",
        position: 0,
      },
    ],
    isVisible: true,
    isFeatured: true,
    isNewArrival: true,
    createdAt,
    updatedAt,
  },
  {
    id: "prod-sweater-tejido-chocolate",
    name: "Sweater Tejido Chocolate",
    slug: "sweater-tejido-chocolate",
    description:
      "Sweater tejido en tono chocolate, suave y abrigado para elevar looks diarios.",
    price: 42900,
    category: "sweaters",
    sizes: ["S", "M", "L"],
    colors: ["Chocolate", "Marrón"],
    stockStatus: "available",
    images: [
      {
        url: "/images/products/sweater-tejido-chocolate/main.webp",
        path: "products/prod-sweater-tejido-chocolate/main.webp",
        alt: "Sweater tejido color chocolate",
        position: 0,
      },
    ],
    isVisible: true,
    isFeatured: true,
    isNewArrival: false,
    createdAt,
    updatedAt,
  },
  {
    id: "prod-campera-negra-urbana",
    name: "Campera Negra Urbana",
    slug: "campera-negra-urbana",
    description:
      "Campera negra de silueta urbana, facil de sumar a outfits de dia y noche.",
    price: 68900,
    category: "camperas",
    sizes: ["S", "M", "L"],
    colors: ["Negro"],
    stockStatus: "available",
    images: [
      {
        url: "/images/products/campera-negra-urbana/main.webp",
        path: "products/prod-campera-negra-urbana/main.webp",
        alt: "Campera negra urbana",
        position: 0,
      },
    ],
    isVisible: true,
    isFeatured: false,
    isNewArrival: true,
    createdAt,
    updatedAt,
  },
  {
    id: "prod-pantalon-sastrero-negro",
    name: "Pantalón Sastrero Negro",
    slug: "pantalon-sastrero-negro",
    description:
      "Pantalón sastrero negro de corte recto, una base elegante para cualquier temporada.",
    price: 53900,
    category: "pantalones",
    sizes: ["36", "38", "40", "42"],
    colors: ["Negro"],
    stockStatus: "sold_out",
    images: [
      {
        url: "/images/products/pantalon-sastrero-negro/main.webp",
        path: "products/prod-pantalon-sastrero-negro/main.webp",
        alt: "Pantalón sastrero negro de corte recto",
        position: 0,
      },
    ],
    isVisible: true,
    isFeatured: false,
    isNewArrival: false,
    createdAt,
    updatedAt,
  },
  {
    id: "prod-buzo-off-white",
    name: "Buzo Off White",
    slug: "buzo-off-white",
    description:
      "Buzo off white de calce relajado, comodo y versatil para looks casuales.",
    price: 37900,
    category: "buzos",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Off white"],
    stockStatus: "available",
    images: [
      {
        url: "/images/products/buzo-off-white/main.webp",
        path: "products/prod-buzo-off-white/main.webp",
        alt: "Buzo off white de calce relajado",
        position: 0,
      },
    ],
    isVisible: true,
    isFeatured: false,
    isNewArrival: true,
    createdAt,
    updatedAt,
  },
  {
    id: "prod-remera-vintage",
    name: "Remera Vintage",
    slug: "remera-vintage",
    description:
      "Remera de inspiracion vintage con textura suave, pensada para uso diario.",
    price: 21900,
    category: "tops",
    sizes: ["S", "M", "L"],
    colors: ["Grafito", "Gris lavado"],
    stockStatus: "available",
    images: [
      {
        url: "/images/products/remera-vintage/main.webp",
        path: "products/prod-remera-vintage/main.webp",
        alt: "Remera vintage gris lavado",
        position: 0,
      },
    ],
    isVisible: true,
    isFeatured: false,
    isNewArrival: false,
    createdAt,
    updatedAt,
  },
  {
    id: "prod-cargo-denim",
    name: "Cargo Denim",
    slug: "cargo-denim",
    description:
      "Pantalón cargo denim con bolsillos laterales y actitud urbana.",
    price: 57900,
    category: "jeans",
    sizes: ["36", "38", "40", "42"],
    colors: ["Azul denim"],
    stockStatus: "ask_stock",
    images: [
      {
        url: "/images/products/cargo-denim/main.webp",
        path: "products/prod-cargo-denim/main.webp",
        alt: "Pantalón cargo denim azul",
        position: 0,
      },
    ],
    isVisible: true,
    isFeatured: false,
    isNewArrival: true,
    createdAt,
    updatedAt,
  },
  {
    id: "prod-polera-basica-blanca",
    name: "Polera Básica Blanca",
    slug: "polera-basica-blanca",
    description:
      "Polera blanca basica de cuello alto, liviana y facil de combinar.",
    price: 29900,
    category: "tops",
    sizes: ["S", "M", "L"],
    colors: ["Blanco"],
    stockStatus: "available",
    images: [
      {
        url: "/images/products/polera-basica-blanca/main.webp",
        path: "products/prod-polera-basica-blanca/main.webp",
        alt: "Polera basica blanca de cuello alto",
        position: 0,
      },
    ],
    isVisible: true,
    isFeatured: true,
    isNewArrival: false,
    createdAt,
    updatedAt,
  },
  {
    id: "prod-conjunto-gris-y-negro",
    name: "Conjunto Gris y Negro",
    slug: "conjunto-gris-y-negro",
    description:
      "Conjunto gris y negro de dos piezas, comodo y pulido para resolver el look completo.",
    price: 74900,
    category: "conjuntos",
    sizes: ["S", "M", "L"],
    colors: ["Gris", "Negro"],
    stockStatus: "available",
    images: [
      {
        url: "/images/products/conjunto-gris-y-negro/main.webp",
        path: "products/prod-conjunto-gris-y-negro/main.webp",
        alt: "Conjunto gris y negro de dos piezas",
        position: 0,
      },
    ],
    isVisible: true,
    isFeatured: true,
    isNewArrival: true,
    createdAt,
    updatedAt,
  },
  {
    id: "prod-accesorio-cartera-bordo",
    name: "Cartera Bordó Mini",
    slug: "cartera-bordo-mini",
    description:
      "Cartera mini bordó para sumar un acento femenino y calido al outfit.",
    price: 32900,
    category: "accesorios",
    sizes: ["Único"],
    colors: ["Bordó"],
    stockStatus: "available",
    images: [
      {
        url: "/images/products/cartera-bordo-mini/main.webp",
        path: "products/prod-accesorio-cartera-bordo/main.webp",
        alt: "Cartera mini color bordó",
        position: 0,
      },
    ],
    isVisible: false,
    isFeatured: false,
    isNewArrival: false,
    createdAt,
    updatedAt,
  },
];
